services:
    _defaults:
        autowire: true
        autoconfigure: true

    Becklyn\Hosting\:
        resource: '../../*'

    Becklyn\Hosting\Git\GitIntegration:
        $projectDir: '%kernel.project_dir%'

    Becklyn\Hosting\Project\ProjectVersion:
        $cachePool: '@cache.app'
