services:
    _defaults:
        autowire: true
        autoconfigure: true

    Becklyn\Hosting\:
        resource: '../../*'

    Becklyn\Hosting\Git\GitIntegration:
        $projectDir: '%kernel.project_dir%'

    Becklyn\Hosting\Project\ProjectVersion:
        $cachePool: '@cache.app'

    Becklyn\Hosting\TrackJS\TrackJSEmbed:
        $assetHelper: '@?Becklyn\AssetsBundle\Helper\AssetHelper'
        $packages: '@?Symfony\Component\Asset\Packages'
        $environment: '%kernel.environment%'
        $isDebug: '%kernel.debug%'

    # Explicitly wire the client, as the actual client is a subclass of the Raven_Client and is therefor
    # not picked up by autowiring.
    Becklyn\Hosting\Sentry\CustomSanitizeDataProcessor:
        $client: '@sentry.client'

    Becklyn\Hosting\Listener\SentryExceptionListener:
        decorates: 'sentry.exception_listener'
        arguments:
            $inner: '@Becklyn\Hosting\Listener\SentryExceptionListener.inner'
