services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $environment: '%kernel.environment%'
            $isDebug: '%kernel.debug%'

    Becklyn\Hosting\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,BecklynHostingBundle.php}'
