services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $isDebug: '%kernel.debug%'

    Becklyn\Hosting\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,BecklynHostingBundle.php}'

    Sentry\Integration\IgnoreErrorsIntegration: ~

    Becklyn\Hosting\Listener\SentryRequestListener:
        decorates: 'Sentry\SentryBundle\EventListener\RequestListener'
        arguments:
            $inner: '@Becklyn\Hosting\Listener\SentryRequestListener.inner'
